parameters:
  keycloak_realm: '%env(resolve:KEYCLOAK_REALM)%'
  keycloak_master_realm: '%env(resolve:KEYCLOAK_MASTER_REALM)%'
  keycloak_url: '%env(resolve:KEYCLOAK_URL)%'
  keycloak_client_id: '%env(resolve:KEYCLOAK_CLIENT_ID)%'
  keycloak_client_secret: '%env(resolve:KEYCLOAK_CLIENT_SECRET)%'
  keycloak_admin_username: '%env(resolve:KEYCLOAK_ADMIN_USERNAME)%'
  keycloak_admin_password: '%env(resolve:KEYCLOAK_ADMIN_PASSWORD)%'
